"""
Django settings for lawyantra_v1 project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-b)3ols+kymn&ca+&*@u#8_)ra*rh07se$y*y-9*w)6tqc4$y4y'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'rest_framework',
    'rest_framework.authtoken',
    'app'
]


AUTH_USER_MODEL = "app.User"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'lawyantra_v1.urls'

WSGI_APPLICATION = 'lawyantra_v1.wsgi.application'
CORS_ORIGIN_ALLOW_ALL = True


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'lawyantra_marketplace_backend',
        'USER': 'admin',
        'PASSWORD': 'xWhY57z6CbRmVSeEQs',
        'HOST':'marketplace-backend-dev.ckkhapdb5dit.ap-south-1.rds.amazonaws.com',
        'PORT':'3306',
    }
}

# if 'RDS_HOSTNAME' in os.environ:
#     DATABASES = {
#         'default': {
#             'ENGINE': 'django.db.backends.mysql',
#             'NAME': os.environ['RDS_DB_NAME'],
#             'USER': os.environ['RDS_USERNAME'],
#             'PASSWORD': os.environ['RDS_PASSWORD'],
#             'HOST': os.environ['RDS_HOSTNAME'],
#             'PORT': os.environ['RDS_PORT'],
#         }
#     }





AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ]
}


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['app/templates','templates',],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


OTP_VALIDITY_PERIOD = 5


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

MEDIA_ROOT = os.path.join(BASE_DIR, r'data/')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'no-reply@lawyantra.com'  # sender's email-id
# password associated with above email-id
EMAIL_HOST_PASSWORD = 'nmmsykevlknghdkh'


EMAIL_CONTACT_US = 'contact@lawyantra.com'


#openAI
OPEN_AI_KEY = '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'
PROMPT_FOR_CLASSIFICATION = """
    You are an Indian Lawyer expert in categorizing case details based on the categories provided.
    Just return the names of the category based on the case_detail provided.
    categories=Human Rights Law,Intellectual Property Law,Consumer Protection Law,Medical Law,
    Real Estate Law,Constitutional Law,Media and Entertainment Law,Criminal Law,Corporate Law,
    Labor Law,Immigration Law,Environmental Law,Family Law,Tax Law,Banking and Finance Law,Civil Law.
    If there are multiple categories, then return multiple categories.
    Keep the response just the name of the category.
    If the response is not related to categories then return with the output=There is no relevant category for the given case detail. Please provide a valid case detail for categorization.
    """
MODEL_FOR_CATEGORIZING="gpt-3.5-turbo"
CATEGORIES_FOR_CLASSIFICATION=[
        "Human Rights Law",
        "Intellectual Property Law",
        "Consumer Protection Law",
        "Medical Law",
        "Real Estate Law",
        "Constitutional Law",
        "Media and Entertainment Law",
        "Criminal Law",
        "Corporate Law",
        "Labor Law",
        "Immigration Law",
        "Environmental Law",
        "Family Law",
        "Tax Law",
        "Banking and Finance Law",
        "Civil Law"
    ]

RESPONSE_OF_GPT="There is no relevant category for the given case detail. Please provide a valid case detail for categorization."
